# -*- coding: utf-8 -*-
"""Linear_Regressin_From_Scratch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGBevmKtvolZhoUv6SE-xikcA-__0wXl
"""

import numpy as np
import matplotlib.pyplot as plt

n = 200
x = np.random.rand(n)

y = np.random.rand(n)

plt.scatter(x,y)

un= np.ones(200).T

newX= np.column_stack((un, x.T))

teta = y.T @ newX @ np.power(newX.T @ newX, -1)

teta-1

plt.plot(teta-1,"r")
plt.scatter(x,y)

alpha = 1
teta2  = np.dot(np.dot(y, newX), np.power(np.dot(newX.T,newX)+ alpha * np.identity(2),-1))

plt.plot(teta2-1, "r")
plt.scatter(x,y)

#x = np.append(x,0.5)
#y = np.append(y,1)

plt.plot(teta2-1, "r")
plt.plot(teta-1,"g")
plt.scatter(x,y)

